/** Published dsh web + pnpm dev:web → browser HMR, with no page reload. */

import { existsSync, globSync } from 'node:fs'
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { chromium } from 'playwright'
import { expect, it } from 'vitest'
import { Context } from '@deepseek-ai/cordis'
import type { Fiber } from '@deepseek-ai/cordis'
import LocalSubprocessRuntime from '@deepseek-ai/dsh-subprocess-local'
import type { SubprocessHandle, SubprocessSpawnSpec } from '@deepseek-ai/dsh-subprocess'
import { readClientBuildRecord } from '../../../scripts/client-build-environment.ts'
import { REPO_ROOT } from './support.ts'

const EDITED_PACKAGE = 'packages/client/ui-conversation'
const HMR_ARTIFACT_PATTERNS = [
  'apps/web/dist/**/*',
  'packages/*/*/lib/client.js{,.map}',
  // The edited package's tsc and tsdown outputs extend beyond its client bundle.
  `${EDITED_PACKAGE}/lib/**/*`,
] as const

function hmrArtifactPaths(): string[] {
  const entries = globSync([...HMR_ARTIFACT_PATTERNS], { cwd: REPO_ROOT, withFileTypes: true })
  return [...new Set(entries
    .filter(entry => entry.isFile())
    .map(entry => join(entry.parentPath, entry.name)))]
    .sort()
}

async function verifyHmrArtifacts(original: ReadonlyMap<string, Buffer>): Promise<void> {
  const currentPaths = hmrArtifactPaths()
  const current = new Set(currentPaths)
  const added = currentPaths.filter(path => !original.has(path))
  const missing = [...original.keys()].filter(path => !current.has(path))
  if (added.length > 0 || missing.length > 0) {
    throw new Error(
      `HMR cleanup changed generated files: added ${added.join(', ') || '(none)'}; missing ${missing.join(', ') || '(none)'}`,
    )
  }
  const changed = (await Promise.all(currentPaths.map(async (path) => {
    const expected = original.get(path)
    return expected !== undefined && (await readFile(path)).equals(expected) ? undefined : path
  }))).filter(path => path !== undefined)
  if (changed.length > 0) throw new Error(`HMR cleanup changed generated bytes: ${changed.join(', ')}`)
}

function spawnSpec(argv: readonly string[], cwd: string, env?: Record<string, string>): SubprocessSpawnSpec {
  return {
    argv,
    cwd,
    stdio: { stdin: 'ignore', stdout: 'pipe', stderr: 'pipe' },
    graceMs: 5_000,
    ...env === undefined ? {} : { env },
  }
}

function waitForOutput(child: SubprocessHandle, pattern: RegExp, label: string): Promise<string> {
  return new Promise((resolveReady, reject) => {
    let output = ''
    let settled = false
    const cleanup = (): void => {
      clearTimeout(timer)
      child.stdout?.off('data', onData)
      child.stderr?.off('data', onData)
    }
    const resolveOnce = (value: string): void => {
      if (settled) return
      settled = true
      cleanup()
      resolveReady(value)
    }
    const rejectOnce = (error: Error): void => {
      if (settled) return
      settled = true
      cleanup()
      reject(error)
    }
    const onData = (chunk: Buffer): void => {
      output += chunk.toString()
      const match = pattern.exec(output)
      if (match === null) return
      resolveOnce(match[1] ?? match[0])
    }
    const timer = setTimeout(() => { rejectOnce(new Error(`${label} not ready:\n${output}`)) }, 60_000)
    child.stdout?.on('data', onData)
    child.stderr?.on('data', onData)
    void child.done.then((outcome) => {
      rejectOnce(new Error(`${label} exited before ready (${JSON.stringify(outcome)}):\n${output}`))
    }, (error: unknown) => {
      rejectOnce(new Error(`${label} failed before ready:\n${output}`, { cause: error }))
    })
  })
}

async function stopTree(child: SubprocessHandle): Promise<void> {
  child.terminate()
  const stopped = await child.waitForExit(AbortSignal.timeout(15_000))
  if (!stopped) throw new Error(`process tree ${String(child.pid)} did not stop after termination escalation`)
  await child.done
}

it('hot-reloads a real client-plugin source edit without refreshing the page', async () => {
  const sourcePath = join(REPO_ROOT, EDITED_PACKAGE, 'src/client/locales.ts')
  const binPath = join(REPO_ROOT, 'apps/cli/lib/bin.js')
  if (!existsSync(binPath)) throw new Error('HMR browser test needs the built dsh bin; run pnpm run build first')
  const clientBuildEnvironment = readClientBuildRecord(REPO_ROOT).environment
  const originalHmrArtifacts = new Map(await Promise.all(
    hmrArtifactPaths().map(async path => [path, await readFile(path)] as const),
  ))
  const originalSource = await readFile(sourcePath)
  const oldText = 'Into the Unknown'
  const sourceNeedle = "'hero.headline': 'Into the Unknown'"
  const newText = `HMR UPDATED ${'x'.repeat(80)}`
  const updatedSource = originalSource.toString().replace(sourceNeedle, `'hero.headline': '${newText}'`)
  if (updatedSource === originalSource.toString()) throw new Error(`HMR source lacks ${JSON.stringify(sourceNeedle)}`)

  const world = await mkdtemp(join(tmpdir(), 'dsh-web-hmr-world-'))
  const subprocessCtx = new Context()
  let subprocessFiber: Fiber | undefined
  let watcher: SubprocessHandle | undefined
  let host: SubprocessHandle | undefined
  let browser: Awaited<ReturnType<typeof chromium.launch>> | undefined
  const failures: unknown[] = []
  try {
    subprocessFiber = await subprocessCtx.plugin(LocalSubprocessRuntime)
    watcher = subprocessCtx.subprocess.spawn(spawnSpec(
      ['pnpm', 'run', 'dev:web'],
      REPO_ROOT,
      { ...clientBuildEnvironment },
    ))
    await waitForOutput(watcher, /dev-web: watching/, 'pnpm run dev:web')
    host = subprocessCtx.subprocess.spawn(spawnSpec(
      [process.execPath, binPath, 'web', '--no-open', '--port', '0'],
      world,
      {
        DEEPSEEK_API_KEY: 'keyless-hmr-no-call',
        DSH_HOME: join(world, '.dsh'),
      },
    ))
    const baseUrl = await waitForOutput(host, /dsh web: (http:\/\/[^\s]+)/, 'built dsh web')
    browser = await chromium.launch()
    const page = await browser.newPage()
    const pageErrors: string[] = []
    page.on('pageerror', error => pageErrors.push(String(error)))
    await page.goto(baseUrl, { waitUntil: 'load' })
    await page.getByText(oldText, { exact: true }).waitFor({ timeout: 15_000 })
    const pageIdentity = await page.evaluate(() => {
      const identity = crypto.randomUUID()
      Object.defineProperty(window, '__dshHmrPageIdentity', { value: identity })
      return identity
    })

    await writeFile(sourcePath, updatedSource)
    await page.getByText(newText, { exact: true }).waitFor({ timeout: 30_000 })
    expect(await page.evaluate(() => (window as Window & { __dshHmrPageIdentity?: string }).__dshHmrPageIdentity))
      .toBe(pageIdentity)
    expect(pageErrors).toEqual([])
  } catch (error) {
    failures.push(error)
  } finally {
    if (watcher !== undefined) await stopTree(watcher).catch((error: unknown) => failures.push(error))
    await writeFile(sourcePath, originalSource).catch((error: unknown) => failures.push(error))
    let currentHmrArtifacts: string[] = []
    try {
      currentHmrArtifacts = hmrArtifactPaths()
    } catch (error) {
      failures.push(error)
    }
    await Promise.all(currentHmrArtifacts
      .filter(path => !originalHmrArtifacts.has(path))
      .map(async (path) => {
        await rm(path, { force: true }).catch((error: unknown) => failures.push(error))
      }))
    await Promise.all([...originalHmrArtifacts].map(async ([path, content]) => {
      await writeFile(path, content).catch((error: unknown) => failures.push(error))
    }))
    try {
      if (!(await readFile(sourcePath)).equals(originalSource)) {
        throw new Error(`HMR cleanup did not restore ${sourcePath}`)
      }
      await verifyHmrArtifacts(originalHmrArtifacts)
    } catch (error) {
      failures.push(error)
    }
    try {
      readClientBuildRecord(REPO_ROOT)
    } catch (error) {
      failures.push(error)
    }
    if (host !== undefined) await stopTree(host).catch((error: unknown) => failures.push(error))
    await browser?.close().catch((error: unknown) => failures.push(error))
    await subprocessFiber?.dispose().catch((error: unknown) => failures.push(error))
    await rm(world, { recursive: true, force: true }).catch((error: unknown) => failures.push(error))
  }
  if (failures.length > 0) throw new AggregateError(failures, 'HMR browser test or cleanup failed')
}, 120_000)
